spring.application.name=gestao_residuos

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

minha.chave.secreta=${JWT_SECRET}

spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=true
spring.flyway.validate-on-migrate=${FLYWAY_VALIDATE_ON_MIGRATE:true}
spring.flyway.locations=classpath:db/migration

server.port=${PORT:8080}
server.forward-headers-strategy=framework

logging.file.name=${LOG_FILE:./logs/gestao-residuos.log}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.persist-authorization=true
springdoc.api-docs.path=/v3/api-docs
